/*** Table: fileobj ***/

CREATE TABLE fileobj (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    component character varying NOT NULL,
    uuid character varying(32) NOT NULL,
    size bigint NOT NULL,
    PRIMARY KEY (id)
);

COMMENT ON TABLE fileobj IS 'file_storage';

CREATE UNIQUE INDEX fileobj_uuid_component_idx ON fileobj(uuid, component);
