/*** Table: feature_layer_transaction ***/

CREATE TABLE feature_layer_transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_id integer NOT NULL,
    epoch integer,
    user_id integer NOT NULL,
    started timestamp without time zone NOT NULL,
    committed timestamp without time zone,
    PRIMARY KEY (id),
    FOREIGN KEY (resource_id) REFERENCES resource (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES auth_principal (id) ON DELETE CASCADE
);

COMMENT ON TABLE feature_layer_transaction IS 'feature_layer';

/*** Table: feature_layer_transaction_operation ***/

CREATE TABLE feature_layer_transaction_operation (
    transaction_id integer NOT NULL,
    seqnum integer NOT NULL,
    payload jsonb NOT NULL,
    params jsonb,
    error jsonb,
    PRIMARY KEY (transaction_id, seqnum),
    FOREIGN KEY (transaction_id) REFERENCES feature_layer_transaction (id) ON DELETE CASCADE
);

COMMENT ON TABLE feature_layer_transaction_operation IS 'feature_layer';

/*** Table: feature_layer_transaction_result ***/

CREATE TABLE feature_layer_transaction_result (
    transaction_id integer NOT NULL,
    seqnum integer NOT NULL,
    value jsonb NOT NULL,
    PRIMARY KEY (transaction_id, seqnum),
    FOREIGN KEY (transaction_id) REFERENCES feature_layer_transaction (id) ON DELETE CASCADE
);

COMMENT ON TABLE feature_layer_transaction_result IS 'feature_layer';

/*** Table: feature_layer_vmeta ***/

CREATE TABLE feature_layer_vmeta (
    resource_id integer NOT NULL,
    epoch integer NOT NULL,
    latest integer NOT NULL,
    started timestamp without time zone NOT NULL,
    updated timestamp without time zone NOT NULL,
    PRIMARY KEY (resource_id),
    CHECK ((
        latest = 1 AND updated = started
    )
    OR (
        latest > 1 AND updated > started
    )),
    FOREIGN KEY (resource_id) REFERENCES resource (id)
);

COMMENT ON TABLE feature_layer_vmeta IS 'feature_layer';

CREATE SEQUENCE feature_layer_vmeta_epoch_seq;

/*** Table: feature_layer_vobj ***/

CREATE TABLE feature_layer_vobj (
    resource_id integer NOT NULL,
    version_id integer NOT NULL,
    tstamp timestamp without time zone NOT NULL,
    user_id integer,
    PRIMARY KEY (resource_id, version_id),
    CONSTRAINT feature_layer_vobj_resource_id__resource_fkey FOREIGN KEY (resource_id) REFERENCES resource (id) ON DELETE CASCADE,
    CONSTRAINT feature_layer_vobj_resource_id__vmeta_fkey FOREIGN KEY (resource_id) REFERENCES feature_layer_vmeta (resource_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES auth_user (principal_id)
);

COMMENT ON TABLE feature_layer_vobj IS 'feature_layer';

/*** Table: layer_field ***/

CREATE TABLE layer_field (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    layer_id integer NOT NULL,
    cls character varying NOT NULL,
    idx integer NOT NULL,
    keyname character varying NOT NULL,
    datatype character varying(50) NOT NULL,
    display_name character varying NOT NULL,
    grid_visibility boolean NOT NULL,
    text_search boolean NOT NULL,
    required boolean NOT NULL,
    lookup_table_id integer,
    PRIMARY KEY (id),
    UNIQUE (layer_id, keyname) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (layer_id, display_name) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (layer_id) REFERENCES resource (id),
    FOREIGN KEY (lookup_table_id) REFERENCES lookup_table (id)
);

COMMENT ON TABLE layer_field IS 'feature_layer';
