/*** Table: webmap ***/

CREATE TABLE webmap (
    id integer NOT NULL,
    root_item_id integer NOT NULL,
    bookmark_resource_id integer,
    draw_order_enabled boolean,
    editable boolean NOT NULL,
    extent_left double precision,
    extent_right double precision,
    extent_bottom double precision,
    extent_top double precision,
    extent_const_left double precision,
    extent_const_right double precision,
    extent_const_bottom double precision,
    extent_const_top double precision,
    title character varying,
    annotation_enabled boolean NOT NULL,
    annotation_default character varying(50) NOT NULL,
    legend_symbols character varying(50),
    measure_srs_id integer,
    options jsonb NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES resource (id),
    FOREIGN KEY (root_item_id) REFERENCES webmap_item (id),
    FOREIGN KEY (bookmark_resource_id) REFERENCES resource (id),
    FOREIGN KEY (measure_srs_id) REFERENCES srs (id) ON DELETE SET NULL
);

COMMENT ON TABLE webmap IS 'webmap';

/*** Table: webmap_annotation ***/

CREATE TABLE webmap_annotation (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    webmap_id integer NOT NULL,
    description character varying,
    style jsonb,
    geom geometry(GEOMETRY, 3857) NOT NULL,
    public boolean NOT NULL,
    user_id integer,
    PRIMARY KEY (id),
    FOREIGN KEY (webmap_id) REFERENCES webmap (id),
    FOREIGN KEY (user_id) REFERENCES auth_principal (id)
);

COMMENT ON TABLE webmap_annotation IS 'webmap';

/*** Table: webmap_item ***/

CREATE TABLE webmap_item (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id integer,
    item_type character varying(50) NOT NULL,
    position integer,
    display_name character varying,
    group_expanded boolean,
    group_enabled boolean,
    group_exclusive boolean,
    layer_style_id integer,
    layer_enabled boolean,
    layer_identifiable boolean,
    layer_transparency double precision,
    layer_min_scale_denom double precision,
    layer_max_scale_denom double precision,
    layer_adapter character varying(50),
    draw_order_position integer,
    legend_symbols character varying(50),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES webmap_item (id),
    FOREIGN KEY (layer_style_id) REFERENCES resource (id)
);

COMMENT ON TABLE webmap_item IS 'webmap';
