/*** {
    "revision": "55b2445f", "parents": ["4c13911a"],
    "date": "2026-09-19T11:04:56",
    "message": "Fix srs_id_seq ownership"
} ***/

DO $$
DECLARE
    v_last_value bigint;
    v_is_called boolean;
BEGIN
    SELECT last_value, is_called
    INTO v_last_value, v_is_called
    FROM srs_id_seq;

    ALTER TABLE srs
        ALTER COLUMN id DROP IDENTITY IF EXISTS,
        ALTER COLUMN id DROP DEFAULT;
    
    DROP SEQUENCE IF EXISTS srs_id_seq;

    ALTER TABLE srs
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME srs_id_seq
            START WITH 990001
            MINVALUE 990001
            MAXVALUE 998999
        );

    PERFORM setval('srs_id_seq', v_last_value, v_is_called);
END $$;