//>>built
define("dojox/css3/transition","dojo/_base/lang dojo/_base/array dojo/Deferred dojo/when dojo/promise/all dojo/on dojo/sniff".split(" "),function(h,g,t,p,u,q,r){var k="transitionend",f="t",l="translate3d(",m=",0,0)";r("webkit")?(f="WebkitT",k="webkitTransitionEnd"):r("mozilla")&&(f="MozT",l="translateX(",m=")");var e=function(b){h.mixin(this,{startState:{},endState:{},node:null,duration:250,"in":!0,direction:1,autoClear:!0});h.mixin(this,b);this.deferred||(this.deferred=new t)};h.extend(e,{play:function(){e.groupedPlay([this])},
_applyState:function(b){var d=this.node.style,a;for(a in b)b.hasOwnProperty(a)&&(d[a]=b[a])},initState:function(){this.node.style[f+"ransitionProperty"]="none";this.node.style[f+"ransitionDuration"]="0ms";this._applyState(this.startState)},_beforeStart:function(){"none"===this.node.style.display&&(this.node.style.display="");this.beforeStart()},_beforeClear:function(){this.node.style[f+"ransitionProperty"]="";this.node.style[f+"ransitionDuration"]="";!0!==this["in"]&&(this.node.style.display="none");
this.beforeClear()},_onAfterEnd:function(){this.deferred.resolve(this.node);this.node.id&&e.playing[this.node.id]===this.deferred&&delete e.playing[this.node.id];this.onAfterEnd()},beforeStart:function(){},beforeClear:function(){},onAfterEnd:function(){},start:function(){this._beforeStart();this._startTime=(new Date).getTime();this._cleared=!1;var b=this;b.node.style[f+"ransitionProperty"]="all";b.node.style[f+"ransitionDuration"]=b.duration+"ms";q.once(b.node,k,function(){b.clear()});this._applyState(this.endState)},
clear:function(){this._cleared||(this._cleared=!0,this._beforeClear(),this._removeState(this.endState),this._onAfterEnd())},_removeState:function(b){var d=this.node.style,a;for(a in b)b.hasOwnProperty(a)&&(d[a]="")}});e.slide=function(b,d){var a=new e(d);a.node=b;var c="0",g="0";a["in"]?c=1===a.direction?"100%":"-100%":g=1===a.direction?"-100%":"100%";a.startState[f+"ransform"]=l+c+m;a.endState[f+"ransform"]=l+g+m;return a};e.fade=function(b,d){var a=new e(d);a.node=b;var c="0",f="0";a["in"]?f="1":
c="1";h.mixin(a,{startState:{opacity:c},endState:{opacity:f}});return a};e.flip=function(b,d){var a=new e(d);a.node=b;a["in"]?(h.mixin(a,{startState:{opacity:"0"},endState:{opacity:"1"}}),a.startState[f+"ransform"]="scale(0,0.8) skew(0,-30deg)",a.endState[f+"ransform"]="scale(1,1) skew(0,0)"):(h.mixin(a,{startState:{opacity:"1"},endState:{opacity:"0"}}),a.startState[f+"ransform"]="scale(1,1) skew(0,0)",a.endState[f+"ransform"]="scale(0,0.8) skew(0,30deg)");return a};var n=function(b){var d=[];g.forEach(b,
function(a){a.id&&e.playing[a.id]&&d.push(e.playing[a.id])});return u(d)};e.getWaitingList=n;e.groupedPlay=function(b){var d=g.filter(b,function(a){return a.node}),d=n(d);g.forEach(b,function(a){a.node.id&&(e.playing[a.node.id]=a.deferred)});p(d,function(){g.forEach(b,function(a){a.initState()});setTimeout(function(){g.forEach(b,function(a){a.start()});q.once(b[b.length-1].node,k,function(){for(var a,c=0;c<b.length-1;c++)0===b[c].deferred.fired||b[c]._cleared||(a=(new Date).getTime()-b[c]._startTime,
a>=b[c].duration&&b[c].clear())});setTimeout(function(){for(var a,c=0;c<b.length;c++)0===b[c].deferred.fired||b[c]._cleared||(a=(new Date).getTime()-b[c]._startTime,a>=b[c].duration&&b[c].clear())},b[0].duration+50)},33)})};e.chainedPlay=function(b){var d=g.filter(b,function(a){return a.node}),d=n(d);g.forEach(b,function(a){a.node.id&&(e.playing[a.node.id]=a.deferred)});p(d,function(){g.forEach(b,function(a){a.initState()});for(var a=1,c=b.length;a<c;a++)b[a-1].deferred.then(h.hitch(b[a],function(){this.start()}));
setTimeout(function(){b[0].start()},33)})};e.playing={};return e});
//# sourceMappingURL=transition.js.map