/*** Table: svg_marker ***/

CREATE TABLE svg_marker (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    svg_marker_library_id integer NOT NULL,
    fileobj_id integer NOT NULL,
    name character varying(255) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (svg_marker_library_id, name),
    FOREIGN KEY (svg_marker_library_id) REFERENCES svg_marker_library (id),
    FOREIGN KEY (fileobj_id) REFERENCES fileobj (id)
);

COMMENT ON TABLE svg_marker IS 'svg_marker_library';

/*** Table: svg_marker_library ***/

CREATE TABLE svg_marker_library (
    id integer NOT NULL,
    stuuid character varying(32),
    tstamp timestamp without time zone,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES resource (id)
);

COMMENT ON TABLE svg_marker_library IS 'svg_marker_library';
