/*** Table: audit_journal ***/

CREATE TABLE audit_journal (
    tstamp timestamp without time zone NOT NULL,
    ident smallint GENERATED BY DEFAULT AS IDENTITY (CYCLE),
    data jsonb NOT NULL,
    PRIMARY KEY (tstamp, ident)
);

COMMENT ON TABLE audit_journal IS 'audit';
