//>>built
define("dojox/jq",["dojo","dijit","dojox","dojo/require!dojo/NodeList-traverse,dojo/NodeList-manipulate,dojo/io/script"],function(d,W,X){d.provide("dojox.jq");d.require("dojo.NodeList-traverse");d.require("dojo.NodeList-manipulate");d.require("dojo.io.script");(function(){function P(a,b){a=(a+"").replace(/<\s*(\w+)([^\/\>]*)\/\s*>/g,function(a,b,d){return-1=="|img|meta|hr|br|input|".indexOf("|"+b+"|")?"\x3c"+b+d+"\x3e\x3c/"+b+"\x3e":a});return d._toDom(a,b)}function D(a){var b=a.indexOf("-");-1!=
b&&(0==b&&(a=a.substring(1)),a=a.replace(/-(\w)/g,function(a,b){return b.toUpperCase()}));return a}function E(a,b){if(a==b)return a;var c={},e;for(e in b)void 0!==c[e]&&c[e]==b[e]||void 0===b[e]||a==b[e]||(d.isObject(a[e])&&d.isObject(b[e])?d.isArray(b[e])?a[e]=b[e]:a[e]=E(a[e],b[e]):a[e]=b[e]);d.isIE&&b&&(e=b.toString,"function"==typeof e&&e!=a.toString&&e!=c.toString&&"\nfunction toString() {\n    [native code]\n}\n"!=e&&(a.toString=b.toString));return a}function F(a,b,c,e){if(e){var h={};h[c]=
e;a.forEach(function(a){d[b](a,h)});return a}return Math.abs(Math.round(d[b](a[0])[c]))}function t(a,b,c,e,h){var f=!1;if(f="none"==a.style.display)a.style.display="block";var l=d.getComputedStyle(a),k=Math.abs(Math.round(d._getContentBox(a,l)[b]));c=c?Math.abs(Math.round(d._getPadExtents(a,l)[b])):0;e=e?Math.abs(Math.round(d._getBorderExtents(a,l)[b])):0;b=h?Math.abs(Math.round(d._getMarginExtents(a,l)[b])):0;f&&(a.style.display="none");return c+k+e+b}function u(a){a=a.split("$$")[0];var b=a.indexOf(".");
-1!=b&&(a=a.substring(0,b));return a}function G(a,b){return 0==b.indexOf("ajax")?d.subscribe(w[b],function(c,e){var d=new f.Event(b);-1!="ajaxComplete|ajaxSend|ajaxSuccess".indexOf(b)?r(a,[d,c.ioArgs.xhr,c.ioArgs.args]):"ajaxError"==b?r(a,[d,c.ioArgs.xhr,c.ioArgs.args,e]):r(a,[d])}):d.connect(a,"on"+b,function(b){r(a,arguments)})}function H(a,b){a=a||[];a=[].concat(a);var c=a[0];c&&c.preventDefault||(c=b&&b.preventDefault?b:new f.Event(b),a.unshift(c));return a}function r(a,b,c){x=!0;b=b||y;9==a.nodeType&&
(a=a.documentElement);var e=a.getAttribute(n);if(e){var h=b[0],f=h.type,l=u(f),e=p[e][l],k;c&&(k=c.apply(a,b));if(!1!==k)for(var g in e)"_connectId"!=g&&(!h._isStrict&&0==g.indexOf(f)||h._isStrict&&g==f)&&(h[d._scopeName+"callbackId"]=g,a=e[g],h.data="undefined"!=typeof a.data?a.data:null,!1!==(k=a.fn.apply(h.target,b))||h._isFake||d.stopEvent(h),h.result=k);return k}}function I(a,b,c,e,h){var f=a[b];if(f){var l=-1!=c.indexOf("."),g=!1;if(e)delete f[e];else if(!l&&!h)g=!0;else if(l)if("."==c.charAt(0))for(var m in f)m.indexOf(c)==
m.length-c.length&&delete f[m];else delete f[c];else for(m in f)if(-1!=m.indexOf("$$")&&f[m].fn==h){delete f[m];break}c=!0;for(m in f)if("_connectId"!=m){c=!1;break}if(g||c)-1!=b.indexOf("ajax")?d.unsubscribe(f._connectId):d.disconnect(f._connectId),delete a[b]}}function J(a){d.isString(a)&&(a="slow"==a?700:"fast"==a?300:500);return a}function K(a){for(var b in a)if(b.indexOf("callback")==b.length-8)return b;return null}d.config.ioPublish=!0;var Q=d.global.$,R=d.global.jQuery,f=d.global.$=d.global.jQuery=
function(a,b){var c=a;if(c)if(d.isString(c))if("\x3c"==c.charAt(0))if(c=P(c),11==c.nodeType)c=c.childNodes;else return f._wrap([c],null,f);else{var e=d._NodeListCtor;d._NodeListCtor=f;var h=b;h&&h._is$?h=h[0]:d.isString(h)&&(h=d.query(h)[0]);c=d.query.call(this,c,h);d._NodeListCtor=e;return c}else{if(d.isFunction(c))return f.ready(c),f;if(c==document||c==window)return f._wrap([c],null,f);if(d.isArray(c)){e=[];for(h=0;h<c.length;h++)-1==d.indexOf(e,c[h])&&e.push(c[h]);return f._wrap(c,null,f)}if("nodeType"in
c)return f._wrap([c],null,f)}else return f._wrap([],null,f);return f._wrap(d._toArray(c),null,f)},z=d.NodeList.prototype,g=f.fn=f.prototype=d.delegate(z);f._wrap=d.NodeList._wrap;var S=/^H\d/i,q=d.query.pseudos;d.mixin(q,{has:function(a,b){return function(a){return f(b,a).length}},visible:function(a,b){return function(a){return"hidden"!=d.style(a,"visible")&&"none"!=d.style(a,"display")}},hidden:function(a,b){return function(a){return"hidden"==a.type||"hidden"==d.style(a,"visible")||"none"==d.style(a,
"display")}},selected:function(a,b){return function(a){return a.selected}},checked:function(a,b){return function(a){return"INPUT"==a.nodeName.toUpperCase()&&a.checked}},disabled:function(a,b){return function(a){return a.getAttribute("disabled")}},enabled:function(a,b){return function(a){return!a.getAttribute("disabled")}},input:function(a,b){return function(a){a=a.nodeName.toUpperCase();return"INPUT"==a||"SELECT"==a||"TEXTAREA"==a||"BUTTON"==a}},button:function(a,b){return function(a){return"INPUT"==
a.nodeName.toUpperCase()&&"button"==a.type||"BUTTON"==a.nodeName.toUpperCase()}},header:function(a,b){return function(a){return a.nodeName.match(S)}}});var L={};d.forEach("text password radio checkbox submit image reset file".split(" "),function(a){L[a]=function(b,c){return function(b){return"INPUT"==b.nodeName.toUpperCase()&&b.type==a}}});d.mixin(q,L);f.browser={mozilla:d.isMoz,msie:d.isIE,opera:d.isOpera,safari:d.isSafari};f.browser.version=d.isIE||d.isMoz||d.isOpera||d.isSafari||d.isWebKit;f.ready=
f.fn.ready=function(a){d.addOnLoad(d.hitch(null,a,f));return this};g._is$=!0;g.size=function(){return this.length};f.prop=function(a,b){return d.isFunction(b)?b.call(a):b};f.className={add:d.addClass,remove:d.removeClass,has:d.hasClass};f.makeArray=function(a){return"undefined"==typeof a?[]:!a.length||d.isString(a)||"location"in a?[a]:d._toArray(a)};f.merge=function(a,b){var c=[a.length,0],c=c.concat(b);a.splice.apply(a,c);return a};f.each=function(a,b){if(d.isArrayLike(a))for(var c=0;c<a.length&&
!1!==b.call(a[c],c,a[c]);c++);else if(d.isObject(a))for(c in a)if(!1===b.call(a[c],c,a[c]))break;return this};g.each=function(a){return f.each.call(this,this,a)};g.eq=function(){var a=f();d.forEach(arguments,function(b){this[b]&&a.push(this[b])},this);return a};g.get=function(a){return a||0==a?this[a]:this};g.index=function(a){a._is$&&(a=a[0]);return this.indexOf(a)};var M=[],T=0,A=d._scopeName+"DataId",N=function(a){var b={};1==a.nodeType&&(b=a.getAttribute(A),b||(b=T++,a.setAttribute(A,b)),(b=M[void 0])||
(b=M[void 0]={}));return b};f.data=function(a,b,c){var e=null;if("events"==b){e=p[a.getAttribute(n)];b=!0;if(e)for(var d in e){b=!1;break}return b?null:e}d=N(a);"undefined"!=typeof c?d[b]=c:e=d[b];return c?this:e};f.removeData=function(a,b){var c=N(a);delete c[b];if(1==a.nodeType){var e=!0,d;for(d in c){e=!1;break}e&&a.removeAttribute(A)}return this};g.data=function(a,b){var c=null;this.forEach(function(e){c=f.data(e,a,b)});return b?this:c};g.removeData=function(a){this.forEach(function(b){f.removeData(b,
a)});return this};g.extend=function(){var a=[this],a=a.concat(arguments);return f.extend.apply(f,a)};f.extend=function(){for(var a=arguments,b,c=0;c<a.length;c++){var e=a[c];e&&d.isObject(e)&&(b?E(b,e):b=e)}return b};f.noConflict=function(a){var b=f;d.global.$=Q;a&&(d.global.jQuery=R);return b};g.attr=function(a,b){if(1==arguments.length&&d.isString(arguments[0])){var c=this[0];if(!c)return null;var e=arguments[0],f=d.attr(c,e),g=c[e];return e in c&&!d.isObject(g)&&"href"!=a?g:f||g}if(d.isObject(a))for(c in a)this.attr(c,
a[c]);else{var l=d.isFunction(b);this.forEach(function(c,e){var f=c[a];a in c&&!d.isObject(f)&&"href"!=a?c[a]=l?b.call(c,e):b:1==c.nodeType&&d.attr(c,a,l?b.call(c,e):b)})}return this};g.removeAttr=function(a){this.forEach(function(b,c){var e=b[a];a in b&&!d.isObject(e)&&"href"!=a?delete b[a]:1==b.nodeType&&("class"==a?b.removeAttribute(a):d.removeAttr(b,a))});return this};g.toggleClass=function(a,b){var c=1<arguments.length;this.forEach(function(e){d.toggleClass(e,a,c?b:!d.hasClass(e,a))});return this};
g.toggle=function(){var a=arguments;if(1<arguments.length&&d.isFunction(arguments[0])){var b=0;return this.bind("click",function(){a[b].apply(this,arguments);b+=1;b>a.length-1&&(b=0)})}var c=1==arguments.length?arguments[0]:void 0;this.forEach(function(b){var e=("undefined"==typeof c?"none"==d.style(b,"display"):c)?"show":"hide";b=f(b);b[e].apply(b,a)});return this};g.hasClass=function(a){return this.some(function(b){return d.hasClass(b,a)})};g.html=g.innerHTML;d.forEach(["filter","slice"],function(a){g[a]=
function(){var b;if(d.isFunction(arguments[0])){var c=arguments[0];arguments[0]=function(a,b){return c.call(a,a,b)}}if("filter"==a&&d.isString(arguments[0]))b=this._filterQueryResult(this,arguments[0]);else{var e=d._NodeListCtor;d._NodeListCtor=g;b=f(z[a].apply(this,arguments));d._NodeListCtor=e}return b._stash(this)}});g.map=function(a){return this._buildArrayFromCallback(a)};f.map=function(a,b){return g._buildArrayFromCallback.call(a,b)};f.inArray=function(a,b){return d.indexOf(b,a)};g.is=function(a){return a?
!!this.filter(a).length:!1};g.not=function(){var a=f.apply(f,arguments);return f(z.filter.call(this,function(b){return-1==a.indexOf(b)}))._stash(this)};g.add=function(){return this.concat.apply(this,arguments)};g.contents=function(){var a=[];this.forEach(function(b){if("IFRAME"==b.nodeName.toUpperCase())(b=b.contentDocument||b.name&&b.document&&document.getElementsByTagName("iframe")[b.name].contentWindow&&document.getElementsByTagName("iframe")[b.name].contentWindow.document||b.name&&document.frames[b.name]&&
document.frames[b.name].document||null)&&a.push(b);else{b=b.childNodes;for(var c=0;c<b.length;c++)a.push(b[c])}});return this._wrap(a)._stash(this)};g.find=function(a){var b=[];this.forEach(function(c){1==c.nodeType&&(b=b.concat(d._toArray(f(a,c))))});return this._getUniqueAsNodeList(b)._stash(this)};g.andSelf=function(){return this.add(this._parent)};g.remove=function(a){a=a?this._filterQueryResult(this,a):this;a.removeData();a.forEach(function(a){a.parentNode.removeChild(a)});return this};f.css=
function(a,b,c){b=D(b);return c?d.style(a,b,c):d.style(a,b)};g.css=function(a,b){if(d.isString(a)){a=D(a);if(2==arguments.length)return d.isString(b)||"zIndex"==a||(b+="px"),this.forEach(function(c){1==c.nodeType&&d.style(c,a,b)}),this;b=d.style(this[0],a);d.isString(b)||"zIndex"==a||(b+="px");return b}for(var c in a)this.css(c,a[c]);return this};g.height=function(a){return F(this,"contentBox","h",a)};g.width=function(a){return F(this,"contentBox","w",a)};g.innerHeight=function(){return t(this[0],
"h",!0)};g.innerWidth=function(){return t(this[0],"w",!0)};g.outerHeight=function(a){return t(this[0],"h",!0,!0,a)};g.outerWidth=function(a){return t(this[0],"w",!0,!0,a)};var p=[],O=1,n=d._scopeName+"eventid",y;f.Event=function(a){if(this==f)return new f.Event(a);"string"==typeof a?this.type=a.replace(/!/,""):d.mixin(this,a);this.timeStamp=(new Date).getTime();this._isFake=!0;this._isStrict=-1!=this.type.indexOf("!")};q=f.Event.prototype={preventDefault:function(){this.isDefaultPrevented=this._true},
stopPropagation:function(){this.isPropagationStopped=this._true},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=this.isPropagationStopped=this._true},_true:function(){return!0},_false:function(){return!1}};d.mixin(q,{isPropagationStopped:q._false,isImmediatePropagationStopped:q._false,isDefaultPrevented:q._false});var x=!1;g.triggerHandler=function(a,b,c){var e=this[0];if(e&&3!=e.nodeType&&8!=e.nodeType)return b=H(b,a),r(e,b,c)};g.trigger=function(a,b,c){b=H(b,a);var e=b[0];
a=u(e.type);y=b;currentExtraFunc=c;var d=null,g=!e.target;this.forEach(function(h){if(3!=h.nodeType&&8!=h.nodeType){9==h.nodeType&&(h=h.documentElement);e._isFake&&(e.currentTarget=h,g&&(e.target=h));if(c){var l=b.slice(1);d=c.apply(h,d=l.concat(d))}if(!1!==d){x=!1;if(h[a])try{d=h[a]()}catch(m){}else if(h["on"+a])try{d=h["on"+a]()}catch(m){}x||(d=r(h,b));h=h.parentNode;!1===d||e.isImmediatePropagationStopped()||e.isPropagationStopped()||!h||1!=h.nodeType||f(h).trigger(a,b,c)}}});currentExtraFunc=
y=null;return this};var U=0;g.bind=function(a,b,c){a=a.split(" ");c||(c=b,b=null);this.forEach(function(d){if(3!=d.nodeType&&8!=d.nodeType){9==d.nodeType&&(d=d.documentElement);var e=d.getAttribute(n);e||(e=O++,d.setAttribute(n,e),p[e]={});for(var f=0;f<a.length;f++){var g=a[f],k=u(g);k==g&&(g=k+"$$"+U++);var m=p[e];m[k]||(m[k]={_connectId:G(d,k)});m[k][g]={fn:c,data:b}}}});return this};g.unbind=function(a,b){var c=a?a[d._scopeName+"callbackId"]:null;a=(a=a&&a.type?a.type:a)?a.split(" "):a;this.forEach(function(d){if(3!=
d.nodeType&&8!=d.nodeType&&(9==d.nodeType&&(d=d.documentElement),d=d.getAttribute(n))&&(d=p[d])){var e=a;if(!e){var e=[],f;for(f in d)e.push(f)}for(var g=0;g<e.length;g++){var k=e[g],m=u(k);if("."==k.charAt(0))for(f in d)I(d,f,k,c,b);else I(d,m,k,c,b)}}});return this};g.one=function(a,b){return this.bind(a,function(){f(this).unbind(a,arguments.callee);return b.apply(this,arguments)})};g._cloneNode=function(a){var b=a.cloneNode(!0);if(1==a.nodeType)for(var c=d.query("["+n+"]",b),e=0,f;f=c[e];e++)if(d.query("["+
n+'\x3d"'+f.getAttribute(n)+'"]',a)[0]){var g=f.getAttribute(n);if(g=p[g]){var l=l=O++;f.setAttribute(n,l);var l=p[l]={},k=void 0;for(k in g){var m=l[k]={_connectId:G(f,k)},B=g[k],v;for(v in B)m[v]={fn:B[v].fn,data:B[v].data}}}}return b};d.getObject("$.event.global",!0);d.forEach("blur focus dblclick click error keydown keypress keyup load mousedown mouseenter mouseleave mousemove mouseout mouseover mouseup submit ajaxStart ajaxSend ajaxSuccess ajaxError ajaxComplete ajaxStop".split(" "),function(a){g[a]=
function(b){b?this.bind(a,b):this.trigger(a);return this}});g.hide=function(a,b){a=J(a);this.forEach(function(c){var e=c.style;"none"!=d.getComputedStyle(c).display&&(e.overflow="hidden",e.display="block",a?d.anim(c,{width:0,height:0,opacity:0},a,null,function(){e.width="";e.height="";e.display="none";return b&&b.call(c)}):(d.style(c,"display","none"),b&&b.call(c)))});return this};g.show=function(a,b){a=J(a);this.forEach(function(c){var e=c.style;if("none"==d.getComputedStyle(c).display)if(a){var f=
parseFloat(e.width),g=parseFloat(e.height);f&&g||(e.display="block",g=d.marginBox(c),f=g.w,g=g.h);e.width=0;e.height=0;e.overflow="hidden";d.attr(c,"opacity",0);e.display="block";d.anim(c,{width:f,height:g,opacity:1},a,null,b?d.hitch(c,b):void 0)}else d.style(c,"display","block"),b&&b.call(c)});return this};f.ajaxSettings={};f.ajaxSetup=function(a){d.mixin(f.ajaxSettings,a)};var w={ajaxStart:"/dojo/io/start",ajaxSend:"/dojo/io/send",ajaxSuccess:"/dojo/io/load",ajaxError:"/dojo/io/error",ajaxComplete:"/dojo/io/done",
ajaxStop:"/dojo/io/stop"},C;for(C in w)0==C.indexOf("ajax")&&function(a){g[a]=function(b){this.forEach(function(c){d.subscribe(w[a],function(d,g){var e=new f.Event(a),h=d&&d.ioArgs,k=h&&h.xhr,h=h&&h.args;return-1!="ajaxComplete|ajaxSend|ajaxSuccess".indexOf(a)?b.call(c,e,k,h):"ajaxError"==a?b.call(c,e,k,h,g):b.call(c,e)})});return this}}(C);var V=d._xhrObj;d._xhrObj=function(a){var b=V.apply(d,arguments);return a&&a.beforeSend&&!1===a.beforeSend(b)?!1:b};f.ajax=function(a){var b=d.delegate(f.ajaxSettings),
c;for(c in a)if("data"==c&&d.isObject(a[c])&&d.isObject(b.data))for(var e in a[c])b.data[e]=a[c][e];else b[c]=a[c];a=b;b=a.url;"async"in a&&(a.sync=!a.async);!1===a.global&&(a.ioPublish=!1);if(a.data)if(e=a.data,d.isString(e))a.content=d.queryToObject(e);else{for(c in e)d.isFunction(e[c])&&(e[c]=e[c]());a.content=e}c=a.dataType;"dataType"in a?("script"==c?c="javascript":"html"==c&&(c="text"),a.handleAs=c):(c=a.handleAs="text",a.guessedType=!0);if("cache"in a)a.preventCache=!a.cache;else if("script"==
a.dataType||"jsonp"==a.dataType)a.preventCache=!0;a.error&&(a._jqueryError=a.error,delete a.error);a.handle=function(b,c){var d="success";if(b instanceof Error)d="timeout"==b.dojoType?"timeout":"error",a._jqueryError&&a._jqueryError(c.xhr,d,b);else{var e=c.args.guessedType&&c.xhr&&c.xhr.responseXML;e&&(b=e);a.success&&a.success(b,d,c.xhr)}a.complete&&a.complete(b,d,c.xhr);return b};e="jsonp"==c;if("javascript"==c){var g=b.indexOf(":"),n=b.indexOf("/");if(0<g&&g<n){var l=b.indexOf("/",n+2);-1==l&&
(l=b.length);if(location.protocol!=b.substring(0,g+1)||location.hostname!=b.substring(n+2,l))e=!0}}if(e)return"jsonp"==c&&(b=a.jsonp,b||((c=a.url.split("?")[1])&&(c=d.queryToObject(c))&&(b=K(c))&&(a.url=a.url.replace(new RegExp("([\x26\\?])?"+b+"\x3d?")+"\x3d?")),b||(b=K(a.content))&&delete a.content[b]),a.jsonp=b||"callback"),b=d.io.script.get(a);b=d.xhr(a.type||"GET",a);return!1===b.ioArgs.xhr?!1:b.ioArgs.xhr};f.getpost=function(a,b,c,e,g){a={url:b,type:a};c&&(d.isFunction(c)&&!e?a.complete=c:a.data=
c);e&&(d.isString(e)&&!g?g=e:a.complete=e);g&&(a.dataType=g);return f.ajax(a)};f.get=d.hitch(f,"getpost","GET");f.post=d.hitch(f,"getpost","POST");f.getJSON=function(a,b,c){return f.getpost("GET",a,b,c,"json")};f.getScript=function(a,b){return f.ajax({url:a,success:b,dataType:"script"})};g.load=function(a,b,c){var e=this[0];if(!e||!e.nodeType||9==e.nodeType)return d.addOnLoad(a),this;e=a.split(/\s+/);a=e[0];var g=e[1],n=c||b,e=d.hitch(this,function(a,b,c){var e=a.match(/\<\s*body[^>]+>.*<\/body\s*>/i);
e&&(a=e);e=d._toDom(a);if(g){var h=f(d.create("div"));h.append(e);e=h.find(g)}else e=f(11==e.nodeType?e.childNodes:e);this.html(e);n&&setTimeout(d.hitch(this,function(){this.forEach(function(d){n.call(d,a,b,c)})}),10)});c?c=e:b=e;e="GET";b&&d.isObject(b)&&(e="POST");f.getpost(e,a,b,c,"html");return this};g.serialize=function(){return""+this.map(function(a){if("FORM"==a.nodeName.toUpperCase())return d.formToQuery(a);var b=(a.type||"").toLowerCase();if(-1=="file|submit|image|reset|button|".indexOf(b)&&
(b=d.fieldToObject(a),a.name&&null!=b)){var c={};c[a.name]=b;return d.objectToQuery(c)}}).join("\x26")};f.param=function(a){return a._is$&&a.serialize?a.serialize():d.isArray(a)?d.map(a,function(a){return f.param(a)}).join("\x26"):d.objectToQuery(a)};f.isFunction=function(){var a=d.isFunction.apply(d,arguments);a&&(a="object"!=typeof arguments[0]);return a}})()});
//# sourceMappingURL=jq.js.map