/*** Table: feature_attachment ***/

CREATE TABLE feature_attachment (
    resource_id integer NOT NULL,
    feature_id integer NOT NULL,
    extension_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fileobj_id integer NOT NULL,
    keyname character varying,
    name character varying,
    mime_type character varying NOT NULL,
    description character varying,
    file_meta jsonb,
    PRIMARY KEY (extension_id, resource_id, feature_id),
    CONSTRAINT feature_attachment_extension_id_unique UNIQUE (resource_id, extension_id),
    CONSTRAINT feature_attachment_keyname_unique UNIQUE (resource_id, feature_id, keyname) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (resource_id) REFERENCES resource (id),
    FOREIGN KEY (fileobj_id) REFERENCES fileobj (id)
);

COMMENT ON TABLE feature_attachment IS 'feature_attachment';

/*** Table: feature_attachment_et ***/

CREATE TABLE feature_attachment_et (
    resource_id integer NOT NULL,
    feature_id integer NOT NULL,
    extension_id integer NOT NULL,
    version_id integer NOT NULL,
    version_op character(1) NOT NULL,
    PRIMARY KEY (resource_id, feature_id, extension_id),
    CONSTRAINT feature_attachment_et_resource_id_version_id_fkey FOREIGN KEY (resource_id, version_id) REFERENCES feature_layer_vobj (resource_id, version_id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (resource_id) REFERENCES feature_layer_vmeta (resource_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

COMMENT ON TABLE feature_attachment_et IS 'feature_attachment';

CREATE INDEX feature_attachment_et_resource_id_version_id_feature_id_idx ON feature_attachment_et(resource_id, version_id, feature_id);

/*** Table: feature_attachment_ht ***/

CREATE TABLE feature_attachment_ht (
    resource_id integer NOT NULL,
    version_id integer NOT NULL,
    feature_id integer NOT NULL,
    extension_id integer NOT NULL,
    version_nid integer NOT NULL,
    version_op character(1) NOT NULL,
    version_nop character(1) NOT NULL,
    fileobj_id integer,
    keyname character varying,
    name character varying,
    mime_type character varying,
    description character varying,
    PRIMARY KEY (resource_id, version_id, feature_id, extension_id),
    CONSTRAINT feature_attachment_ht_fileobj_id_fkey FOREIGN KEY (fileobj_id) REFERENCES fileobj (id),
    CONSTRAINT feature_attachment_ht_resource_id_version_nid_fkey FOREIGN KEY (resource_id, version_nid) REFERENCES feature_layer_vobj (resource_id, version_id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT feature_attachment_ht_range_idx EXCLUDE USING gist(int4range(resource_id, resource_id, '[]') WITH &&, int4range(version_id, version_nid) WITH &&, int4range(feature_id, feature_id, '[]') WITH &&, int4range(extension_id, extension_id, '[]') WITH &&),
    FOREIGN KEY (resource_id) REFERENCES feature_layer_vmeta (resource_id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

COMMENT ON TABLE feature_attachment_ht IS 'feature_attachment';
