//>>built
define("dojox/dtl/contrib/dijit","dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/query ../_base ../dom dojo/parser dojo/_base/sniff".split(" "),function(g,m,r,n,h,u,p,t){function k(c){var b=c.cloneNode(!0);t("ie")&&n("script",b).forEach("item.text \x3d this[index].text;",n("script",c));return b}var d=g.getObject("contrib.dijit",!0,h);d.AttachNode=g.extend(function(c,b){this._keys=c;this._object=b},{render:function(c,b){if(!this._rendered){this._rendered=!0;for(var a=0,e;e=this._keys[a];a++)c.getThis()[e]=
this._object||b.getParent()}return b},unrender:function(c,b){if(this._rendered){this._rendered=!1;for(var a=0,e;e=this._keys[a];a++)c.getThis()[e]===(this._object||b.getParent())&&delete c.getThis()[e]}return b},clone:function(c){return new this.constructor(this._keys,this._object)}});d.EventNode=g.extend(function(c,b){this._command=c;for(var a,e=c.split(/\s*,\s*/),d=g.trim,h=[],q=[];a=e.pop();)if(a){var l=null;-1!=a.indexOf(":")?(l=a.split(":"),a=d(l[0]),l=d(l.slice(1).join(":"))):a=d(a);l||(l=a);
h.push(a);q.push(l)}this._types=h;this._fns=q;this._object=b;this._rendered=[]},{_clear:!1,render:function(c,b){for(var a=0,d;d=this._types[a];a++){this._clear||this._object||(b.getParent()[d]=null);var f=this._fns[a],k;-1!=f.indexOf(" ")&&(this._rendered[a]&&(m.disconnect(this._rendered[a]),this._rendered[a]=!1),k=r.map(f.split(" ").slice(1),function(a){return(new h._Filter(a)).resolve(c)}),f=f.split(" ",2)[0]);this._rendered[a]||(this._object?(g.isArray(k),this._rendered[a]=m.connect(this._object,
d,c.getThis(),f)):this._rendered[a]=b.addEvent(c,d,f,k))}this._clear=!0;return b},unrender:function(c,b){for(;this._rendered.length;)m.disconnect(this._rendered.pop());return b},clone:function(){return new this.constructor(this._command,this._object)}});d.DojoTypeNode=g.extend(function(c,b){this._node=c;this._parsed=b;var a=c.getAttribute("dojoAttachEvent")||c.getAttribute("data-dojo-attach-event");a&&(this._events=new d.EventNode(g.trim(a)));if(a=c.getAttribute("dojoAttachPoint")||c.getAttribute("data-dojo-attach-point"))this._attach=
new d.AttachNode(g.trim(a).split(/\s*,\s*/));b?(c=k(c),a=d.widgetsInTemplate,d.widgetsInTemplate=!1,this._template=new h.DomTemplate(c),d.widgetsInTemplate=a):this._dijit=p.instantiate([k(c)])[0]},{render:function(c,b){if(this._parsed){var a=new h.DomBuffer;this._template.render(c,a);var a=k(a.getRootNode()),d=document.createElement("div");d.appendChild(a);var f=d.innerHTML;d.removeChild(a);f!=this._rendered&&(this._rendered=f,this._dijit&&this._dijit.destroyRecursive(),this._dijit=p.instantiate([a])[0])}a=
this._dijit.domNode;this._events&&(this._events._object=this._dijit,this._events.render(c,b));this._attach&&(this._attach._object=this._dijit,this._attach.render(c,b));return b.concat(a)},unrender:function(c,b){return b.remove(this._dijit.domNode)},clone:function(){return new this.constructor(this._node,this._parsed)}});g.mixin(d,{widgetsInTemplate:!0,dojoAttachPoint:function(c,b){return new d.AttachNode(b.contents.slice(-1!==b.contents.indexOf("data-")?23:16).split(/\s*,\s*/))},dojoAttachEvent:function(c,
b){return new d.EventNode(b.contents.slice(-1!==b.contents.indexOf("data-")?23:16))},dojoType:function(c,b){var a=!1;" parsed"==b.contents.slice(-7)&&(a=!0);var e=-1!==b.contents.indexOf("data-")?b.contents.slice(15):b.contents.slice(9),e=a?e.slice(0,-7):e.toString();if(d.widgetsInTemplate){var f=c.swallowNode();f.setAttribute("data-dojo-type",e);return new d.DojoTypeNode(f,a)}return new h.AttributeNode("data-dojo-type",e)},on:function(c,b){var a=b.contents.split();return new d.EventNode(a[0]+":"+
a.slice(1).join(" "))}});d["data-dojo-type"]=d.dojoType;d["data-dojo-attach-point"]=d.dojoAttachPoint;d["data-dojo-attach-event"]=d.dojoAttachEvent;h.register.tags("dojox.dtl.contrib",{dijit:["attr:dojoType","attr:data-dojo-type","attr:dojoAttachPoint","attr:data-dojo-attach-point",["attr:attach","dojoAttachPoint"],["attr:attach","data-dojo-attach-point"],"attr:dojoAttachEvent","attr:data-dojo-attach-event",[/(attr:)?on(click|key(up))/i,"on"]]});return d});
//# sourceMappingURL=dijit.js.map