//>>built
require({cache:{"url:dojox/form/resources/FilePickerTextBox.html":'\x3cdiv class\x3d"dijit dijitReset dijitInlineTable dijitLeft"\n\tid\x3d"widget_${id}"\n\trole\x3d"combobox" tabIndex\x3d"-1"\n\t\x3e\x3cdiv style\x3d"overflow:hidden;"\n\t\t\x3e\x3cdiv class\x3d\'dijitReset dijitRight dijitButtonNode dijitArrowButton dijitDownArrowButton\'\n\t\t\tdojoAttachPoint\x3d"downArrowNode,_buttonNode,_popupStateNode" role\x3d"presentation"\n\t\t\t\x3e\x3cdiv class\x3d"dijitArrowButtonInner"\x3e\x26thinsp;\x3c/div\n\t\t\t\x3e\x3cdiv class\x3d"dijitArrowButtonChar"\x3e\x26#9660;\x3c/div\n\t\t\x3e\x3c/div\n\t\t\x3e\x3cdiv class\x3d"dijitReset dijitValidationIcon"\x3e\x3cbr\x3e\x3c/div\n\t\t\x3e\x3cdiv class\x3d"dijitReset dijitValidationIconText"\x3e\x26Chi;\x3c/div\n\t\t\x3e\x3cdiv class\x3d"dijitReset dijitInputField"\n\t\t\t\x3e\x3cinput type\x3d"text" autocomplete\x3d"off" ${!nameAttrSetting} class\x3d\'dijitReset\'\n\t\t\t\tdojoAttachEvent\x3d\'onkeypress:_onKey\' \n\t\t\t\tdojoAttachPoint\x3d\'textbox,focusNode\' role\x3d"textbox" aria-haspopup\x3d"true" aria-autocomplete\x3d"list"\n\t\t/\x3e\x3c/div\n\t\x3e\x3c/div\n\x3e\x3c/div\x3e\n'}});
define("dojox/form/FilePickerTextBox","dojo/_base/lang dojo/_base/array dojo/_base/event dojo/window dijit/focus dijit/registry dijit/form/_TextBoxMixin dijit/form/ValidationTextBox dijit/_HasDropDown dojox/widget/FilePicker dojo/text!./resources/FilePickerTextBox.html dojo/_base/declare dojo/keys".split(" "),function(f,r,m,u,v,w,p,x,y,z,A,B,d){return B("dojox.form.FilePickerTextBox",[x,y],{baseClass:"dojoxFilePickerTextBox",templateString:A,searchDelay:500,valueItem:null,numPanes:2.25,postMixInProperties:function(){this.inherited(arguments);
this.dropDown=new z(this.constraints)},postCreate:function(){this.inherited(arguments);this.connect(this.dropDown,"onChange",this._onWidgetChange);this.connect(this.focusNode,"onblur","_focusBlur");this.connect(this.focusNode,"onfocus","_focusFocus");this.connect(this.focusNode,"ondblclick",function(){p.selectInputText(this.focusNode)})},_setValueAttr:function(a,c,b){if(!this._searchInProgress){this.inherited(arguments);a=a||"";var e=this.dropDown.get("pathValue")||"";a!==e&&(this._skip=!0,e=f.hitch(this,
"_setBlurValue"),this.dropDown._setPathValueAttr(a,!b,this._settingBlurValue?e:null))}},_onWidgetChange:function(a){if(!a&&this.focusNode.value)this._hasValidPath=!1,this.focusNode.value="";else{this.valueItem=a;if(a=this.dropDown._getPathValueAttr(a))this._hasValidPath=!0;this._skip||this._setValueAttr(a,void 0,!0);delete this._skip}this.validate()},startup:function(){this.dropDown._started||this.dropDown.startup();this.inherited(arguments)},openDropDown:function(){this.dropDown.domNode.style.width=
"0px";"minPaneWidth"in(this.constraints||{})||this.dropDown.set("minPaneWidth",this.domNode.offsetWidth/this.numPanes);this.inherited(arguments)},toggleDropDown:function(){this.inherited(arguments);this._opened&&this.dropDown.set("pathValue",this.get("value"))},_focusBlur:function(a){a.explicitOriginalTarget!=this.focusNode||this._allowBlur?this._menuFocus&&(this.dropDown._updateClass(this._menuFocus,"Item",{Hover:!1}),delete this._menuFocus):window.setTimeout(f.hitch(this,function(){this._allowBlur||
this.focus()}),1)},_focusFocus:function(a){this._menuFocus&&this.dropDown._updateClass(this._menuFocus,"Item",{Hover:!1});delete this._menuFocus;if(a=v.curNode)if(a=w.byNode(a))this._menuFocus=a.domNode;this._menuFocus&&this.dropDown._updateClass(this._menuFocus,"Item",{Hover:!0});delete this._allowBlur},_onBlur:function(){this._allowBlur=!0;delete this.dropDown._savedFocus;this.inherited(arguments)},_setBlurValue:function(){this.dropDown&&!this._settingBlurValue?(this._settingBlurValue=!0,this.set("value",
this.focusNode.value)):(delete this._settingBlurValue,this.inherited(arguments))},parse:function(a,c){if(this._hasValidPath||this._hasSelection)return a;var b=this.dropDown,e=b.topDir,d=b.pathSeparator,b=b.get("pathValue"),k=function(a){e.length&&0===a.indexOf(e)&&(a=a.substring(e.length));d&&a[a.length-1]==d&&(a=a.substring(0,a.length-1));return a},b=k(b);if(k(a)==b)return a},_startSearchFromInput:function(){var a=this.dropDown,c=this.focusNode,b=c.value,d=b,h=a.topDir;this._hasSelection&&p.selectInputText(c,
d.length);this._hasSelection=!1;h.length&&0===b.indexOf(h)&&(b=b.substring(h.length));var k=b.split(a.pathSeparator),m=f.hitch(this,function(b){var e=k[b],g=a.getChildren()[b],q;this._searchInProgress=!0;var h=f.hitch(this,function(){delete this._searchInProgress});!e&&!g||this._opened||this.toggleDropDown();if(e&&g){var t=f.hitch(this,function(){q&&this.disconnect(q);delete q;var l=g._menu.getChildren(),f=r.filter(l,function(a){return a.label==e})[0],n=r.filter(l,function(a){return 0===a.label.indexOf(e)})[0];
if(f&&(k.length>b+1&&f.children||!f.children))b++,g._menu.onItemClick(f,{type:"internal",stopPropagation:function(){},preventDefault:function(){}}),k[b]?m(b):h();else{g._setSelected(null);if(n&&k.length===b+1){a._setInProgress=!0;a._removeAfter(g);delete a._setInProgress;l=n.label;n.children&&(l+=a.pathSeparator);l=l.substring(e.length);window.setTimeout(function(){u.scrollIntoView(n.domNode)},1);c.value=d+l;p.selectInputText(c,d.length);this._hasSelection=!0;try{n.focusNode.focus()}catch(C){}}else this._menuFocus&&
this.dropDown._updateClass(this._menuFocus,"Item",{Hover:!1,Focus:!1}),delete this._menuFocus;h()}});g.isLoaded?t():q=this.connect(g,"onLoad",t)}else g&&(g._setSelected(null),a._setInProgress=!0,a._removeAfter(g),delete a._setInProgress),h()});m(0)},_onKey:function(a){if(!this.disabled&&!this.readOnly){var c=a.charOrCode;c==d.DOWN_ARROW&&(this._allowBlur=!0);if(c==d.ENTER&&this._opened)this.dropDown.onExecute(),p.selectInputText(this.focusNode,this.focusNode.value.length),this._hasSelection=!1,m.stop(a);
else if(c!=d.RIGHT_ARROW&&c!=d.LEFT_ARROW&&c!=d.TAB||!this._hasSelection){this.inherited(arguments);var b=!1;c!=d.BACKSPACE&&c!=d.DELETE||!this._hasSelection?b=c==d.BACKSPACE||c==d.DELETE||" "==c?!0:""!==a.keyChar:this._hasSelection=!1;this._searchTimer&&window.clearTimeout(this._searchTimer);delete this._searchTimer;b&&(this._hasSelection=this._hasValidPath=!1,this._searchTimer=window.setTimeout(f.hitch(this,"_startSearchFromInput"),this.searchDelay+1))}else this._startSearchFromInput(),m.stop(a)}}})});
//# sourceMappingURL=FilePickerTextBox.js.map