//>>built
define("dojox/mobile/_compat","dojo/_base/array dojo/_base/config dojo/_base/connect dojo/_base/fx dojo/_base/lang dojo/sniff dojo/_base/window dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/dom-attr dojo/fx dojo/fx/easing dojo/ready dojo/uacss dijit/registry dojox/fx dojox/fx/flip ./EdgeToEdgeList ./IconContainer ./ProgressIndicator ./RoundRect ./RoundRectList ./ScrollableView ./Switch ./View ./Heading require".split(" "),function(y,u,p,v,g,f,k,z,q,r,l,H,m,I,A,J,B,C,K,w,
t,D,E,n,F,L,G,M,x){var b=g.getObject("dojox.mobile",!0);f("webkit")||10===f("ie")||!f("ie")&&6<f("trident")||(g.extend(G,{_doTransition:function(a,d,c,e){this.wakeUp(d);var b;if(c&&"none"!=c){if("slide"==c||"cover"==c||"reveal"==c){var h=a.offsetWidth;c=m.slideTo({node:a,duration:400,left:-h*e,top:l.get(a,"top")});b=m.slideTo({node:d,duration:400,left:0,top:l.get(d,"top")});d.style.position="absolute";d.style.left=h*e+"px";d.style.display="";e=m.combine([c,b]);p.connect(e,"onEnd",this,function(){if(this._inProgress){a.style.display=
"none";a.style.left="0px";d.style.position="relative";var c=B.byNode(d);c&&!z.contains(c.domNode,"out")&&(c.containerNode.style.paddingTop="");this.invokeCallback()}})}else"slidev"==c||"coverv"==c||"reavealv"==c?(h=a.offsetHeight,c=m.slideTo({node:a,duration:400,left:0,top:-h*e}),b=m.slideTo({node:d,duration:400,left:0,top:0}),d.style.position="absolute",d.style.top=h*e+"px",d.style.left="0px",d.style.display="",e=m.combine([c,b]),p.connect(e,"onEnd",this,function(){this._inProgress&&(a.style.display=
"none",d.style.position="relative",this.invokeCallback())})):"flip"==c?(e=C.flip({node:a,dir:"right",depth:.5,duration:400}),d.style.position="absolute",d.style.left="0px",p.connect(e,"onEnd",this,function(){this._inProgress&&(a.style.display="none",d.style.position="relative",d.style.display="",this.invokeCallback())})):(e=m.chain([v.fadeOut({node:a,duration:600}),v.fadeIn({node:d,duration:600})]),d.style.position="absolute",d.style.left="0px",d.style.display="",l.set(d,"opacity",0),p.connect(e,
"onEnd",this,function(){this._inProgress&&(a.style.display="none",d.style.position="relative",l.set(a,"opacity",1),this.invokeCallback())}));e.play()}else d.style.display="",a.style.display="none",d.style.left="0px",this.invokeCallback()},wakeUp:function(a){if(f("ie")&&!a._wokeup){a._wokeup=!0;var d=a.style.display;a.style.display="";for(var c=a.getElementsByTagName("*"),e=0,b=c.length;e<b;e++){var h=c[e].style.display;c[e].style.display="none";c[e].style.display="";c[e].style.display=h}a.style.display=
d}}}),g.extend(D,{scale:function(a){if(f("ie"))a={w:a,h:a},r.setMarginBox(this.domNode,a),r.setMarginBox(this.containerNode,a);else if(f("ff")){var d=a/40;l.set(this.containerNode,{MozTransform:"scale("+d+")",MozTransformOrigin:"0 0"});r.setMarginBox(this.domNode,{w:a,h:a});r.setMarginBox(this.containerNode,{w:a/d,h:a/d})}}}),f("ie")&&(g.extend(E,{buildRendering:function(){b.createRoundRect(this);this.domNode.className="mblRoundRect"}}),n._addChild=n.prototype.addChild,n._postCreate=n.prototype.postCreate,
g.extend(n,{buildRendering:function(){b.createRoundRect(this,!0);this.domNode.className="mblRoundRectList";f("ie")&&f("dojo-bidi")&&!this.isLeftToRight()&&(this.domNode.className="mblRoundRectList mblRoundRectListRtl")},postCreate:function(){n._postCreate.apply(this,arguments);this.redrawBorders()},addChild:function(a,d){n._addChild.apply(this,arguments);this.redrawBorders();b.applyPngFilter&&b.applyPngFilter(a.domNode)},redrawBorders:function(){if(!(this instanceof w))for(var a=!1,d=this.containerNode.childNodes.length-
1;0<=d;d--){var c=this.containerNode.childNodes[d];"LI"==c.tagName&&(c.style.borderBottomStyle=a?"solid":"none",a=!0)}}}),g.extend(w,{buildRendering:function(){this.domNode=this.containerNode=this.srcNodeRef||k.doc.createElement("ul");this.domNode.className="mblEdgeToEdgeList"}}),t._addChild=t.prototype.addChild,g.extend(t,{addChild:function(a,d){t._addChild.apply(this,arguments);b.applyPngFilter&&b.applyPngFilter(a.domNode)}}),g.mixin(b,{createRoundRect:function(a,d){var c,e;a.domNode=k.doc.createElement("div");
a.domNode.style.padding="0px";a.domNode.style.backgroundColor="transparent";a.domNode.style.border="none";a.containerNode=k.doc.createElement(d?"ul":"div");a.containerNode.className="mblRoundRectContainer";if(a.srcNodeRef){a.srcNodeRef.parentNode.replaceChild(a.domNode,a.srcNodeRef);c=0;for(e=a.srcNodeRef.childNodes.length;c<e;c++)a.containerNode.appendChild(a.srcNodeRef.removeChild(a.srcNodeRef.firstChild));a.srcNodeRef=null}a.domNode.appendChild(a.containerNode);for(c=0;5>=c;c++)e=q.create("div"),
e.className="mblRoundCorner mblRoundCorner"+c+"T",a.domNode.insertBefore(e,a.containerNode),e=q.create("div"),e.className="mblRoundCorner mblRoundCorner"+c+"B",a.domNode.appendChild(e)}}),g.extend(F,{postCreate:function(){var a=q.create("div",{className:"mblDummyForIE",innerHTML:"\x26nbsp;"},this.containerNode,"first");l.set(a,{position:"relative",marginBottom:"-2px",fontSize:"1px"})}})),6>=f("ie")&&(b.applyPngFilter=function(a){a=a||k.body();a=a.getElementsByTagName("IMG");for(var d=x.toUrl("dojo/resources/blank.gif"),
c=0,e=a.length;c<e;c++){var b=a[c],h=b.offsetWidth,f=b.offsetHeight;if(0===h||0===f){if("none"!=l.get(b,"display"))continue;b.style.display="";h=b.offsetWidth;f=b.offsetHeight;b.style.display="none";if(0===h||0===f)continue}var g=b.src;-1==g.indexOf("resources/blank.gif")&&(b.src=d,b.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+g+"')",b.style.width=h+"px",b.style.height=f+"px")}},!b._disableBgFilter&&b.createDomButton&&(b._createDomButton_orig=b.createDomButton,
b.createDomButton=function(a,d,c){var e=b._createDomButton_orig.apply(this,arguments);if(e&&e.className&&-1!==e.className.indexOf("mblDomButton")){var f=function(){if(e.currentStyle&&e.currentStyle.backgroundImage.match(/url.*(mblDomButton.*\.png)/)){var a=RegExp.$1,a=x.toUrl("dojox/mobile/themes/common/domButtons/compat/")+a;e.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+a+"',sizingMethod\x3d'crop')";e.style.background="none"}};setTimeout(f,1E3);setTimeout(f,
5E3)}return e})),b.loadCssFile=function(a){b.loadedCssFiles||(b.loadedCssFiles=[]);k.doc.createStyleSheet?setTimeout(function(a){return function(){var c=k.doc.createStyleSheet(a);c&&b.loadedCssFiles.push(c.owningElement)}}(a),0):b.loadedCssFiles.push(q.create("link",{href:a,type:"text/css",rel:"stylesheet"},k.doc.getElementsByTagName("head")[0]))},b.loadCss=function(a){if(!b._loadedCss){var d={};y.forEach(b.getCssPaths(),function(a){d[a]=!0});b._loadedCss=d}g.isArray(a)||(a=[a]);for(var c=0;c<a.length;c++){var e=
a[c];b._loadedCss[e]||(b._loadedCss[e]=!0,b.loadCssFile(e))}},b.getCssPaths=function(){var a=[],d,c,b=k.doc.styleSheets;for(d=0;d<b.length;d++)if(!b[d].href){var f=b[d].cssRules||b[d].imports;if(f)for(c=0;c<f.length;c++)f[c].href&&a.push(f[c].href)}b=k.doc.getElementsByTagName("link");d=0;for(c=b.length;d<c;d++)b[d].href&&a.push(b[d].href);return a},b.loadCompatPattern=/\/mobile\/themes\/.*\.css$/,b.loadCompatCssFiles=function(a){if(f("ie")&&!a)setTimeout(function(){b.loadCompatCssFiles(!0)},0);else{b._loadedCss=
void 0;a=b.getCssPaths();f("dojo-bidi")&&(a=b.loadRtlCssFiles(a));for(var d=0;d<a.length;d++){var c=a[d];!c.match(u.mblLoadCompatPattern||b.loadCompatPattern)&&-1===location.href.indexOf("mobile/tests/")||-1!==c.indexOf("-compat.css")||(c=c.substring(0,c.length-4)+"-compat.css",b.loadCss(c))}}},f("dojo-bidi")&&(b.loadRtlCssFiles=function(a){for(var d=0;d<a.length;d++){var c=a[d];if(-1==c.indexOf("_rtl")){var e=c.substr(c.lastIndexOf("/")+1);-1!="android.css blackberry.css custom.css iphone.css holodark.css base.css Carousel.css ComboBox.css IconContainer.css IconMenu.css ListItem.css RoundRectCategory.css SpinWheel.css Switch.css TabBar.css ToggleButton.css ToolBarButton.css ProgressIndicator.css Accordion.css GridLayout.css FormLayout.css".indexOf(e)&&
(c=c.replace(".css","_rtl.css"),a.push(c),b.loadCss(c))}}return a}),b.hideAddressBar=function(a,d){!1!==d&&b.resizeAll()},A(function(){!1!==u.mblLoadCompatCssFiles&&b.loadCompatCssFiles();b.applyPngFilter&&b.applyPngFilter()}));return b});
//# sourceMappingURL=_compat.js.map