//>>built
define("dojox/charting/action2d/_IndicatorElement","dojo/_base/lang dojo/_base/array dojo/_base/declare ../plot2d/Indicator dojo/has ../plot2d/common ../axis2d/common dojox/gfx".split(" "),function(p,x,l,y,v){var w=function(b,a,e){var f,c=b?{x:a[0],y:e[0][0]}:{x:e[0][0],y:a[0]};1<a.length&&(f=b?{x:a[1],y:e[1][0]}:{x:e[1][0],y:a[1]});return[c,f]};l=l("dojox.charting.action2d._IndicatorElement",y,{constructor:function(b,a){a||(a={});this.inter=a.inter},_updateVisibility:function(b,a,e){var f="x"==e?
this._hAxis:this._vAxis,c=f.getWindowScale();this.chart.setAxisWindow(f.name,c,f.getWindowOffset()+(b[e]-a[e])/c);this._noDirty=!0;this.chart.render();this._noDirty=!1;this._initTrack()},_trackMove:function(){this._updateIndicator(this.pageCoord);this._tracker=setTimeout(p.hitch(this,this._trackMove),100)},_initTrack:function(){this._tracker||(this._tracker=setTimeout(p.hitch(this,this._trackMove),500))},stopTrack:function(){this._tracker&&(clearTimeout(this._tracker),this._tracker=null)},render:function(){if(this.isDirty()){var b=
this.inter,a=b.plot,e=b.opt.vertical;this.opt.offset=b.opt.offset||(e?{x:0,y:5}:{x:5,y:0});b.opt.labelFunc&&(this.opt.labelFunc=function(a,c,g,d,h){a=w(e,c,g);return b.opt.labelFunc(a[0],a[1],d,h)});b.opt.fillFunc&&(this.opt.fillFunc=function(a,c,g){a=w(e,c,g);return b.opt.fillFunc(a[0],a[1])});this.opt=p.delegate(b.opt,this.opt);this.pageCoord?(this.opt.values=[],this.opt.labels=this.secondCoord?"trend":"markers"):(this.opt.values=null,this.inter.onChange({}));this.hAxis=a.hAxis;this.vAxis=a.vAxis;
this.inherited(arguments)}},_updateIndicator:function(){var b=this._updateCoordinates(this.pageCoord,this.secondCoord);if(1<b.length){var a=this.opt.vertical;this._data=[];this.opt.values=[];x.forEach(b,function(b){b&&(this.opt.values.push(a?b.x:b.y),this._data.push([a?b.y:b.x]))},this);this.inherited(arguments)}else this.inter.onChange({})},_renderText:function(b,a,e,f,c,g,d,h){this.inter.opt.labels&&this.inherited(arguments);var k=w(this.opt.vertical,d,h);this.inter.onChange({start:k[0],end:k[1],
label:a})},_updateCoordinates:function(b,a){v("dojo-bidi")&&this._checkXCoords(b,a);var e=this.inter,f=e.plot,c=e.opt.vertical,g=this.chart.getAxis(f.hAxis),d=this.chart.getAxis(f.vAxis),h=g.name,k=d.name,l=g.getScaler().bounds,p=d.getScaler().bounds,d=c?"x":"y",g=c?h:k,t=c?l:p;if(a){var m;c?b.x>a.x&&(m=a,a=b,b=m):b.y>a.y&&(m=a,a=b,b=m)}var r=f.toData(b),n;a&&(n=f.toData(a));var q={};q[h]=l.from;q[k]=p.from;m=f.toPage(q);q[h]=l.to;q[k]=p.to;h=f.toPage(q);if(r[g]<t.from){if(n||!e.opt.autoScroll||e.opt.mouseOver){if(e.opt.mouseOver)return[];
b[d]=m[d]}else return this._updateVisibility(b,m,d),[];r=f.toData(b)}else if(r[g]>t.to){if(n||!e.opt.autoScroll||e.opt.mouseOver){if(e.opt.mouseOver)return[];b[d]=h[d]}else return this._updateVisibility(b,h,d),[];r=f.toData(b)}var e=this._snapData(r,d,c),u;if(null==e.y)return[];a&&(n[g]<t.from?(a[d]=m[d],n=f.toData(a)):n[g]>t.to&&(a[d]=h[d],n=f.toData(a)),u=this._snapData(n,d,c),null==u.y&&(u=null));return[e,u]},_snapData:function(b,a,e){var f=this.chart.getSeries(this.inter.opt.series).data,c,g,
d=f.length;for(c=0;c<d;++c)if(g=f[c],null!=g)if("number"==typeof g){if(c+1>b[a])break}else if(g[a]>b[a])break;v("dojo-bidi")&&(c=d-c,g=f[c],1<b[a]&&(b[a]=d-b[a]+1,b[a]>d&&(b[a]=d-.1)));var h,k;"number"==typeof g?(d=c+1,0<c&&(h=c,k=f[c-1])):(d=g.x,g=g.y,0<c&&(h=f[c-1].x,k=f[c-1].y));0<c&&b[a]<=(e?(d+h)/2:(g+k)/2)&&(d=h,g=k);return{x:d,y:g}},cleanGroup:function(b){this.inherited(arguments);this.group.moveToFront();return this},isDirty:function(){return!this._noDirty&&(this.dirty||this.inter.plot.isDirty())}});
v("dojo-bidi")&&l.extend({_checkXCoords:function(b,a){this.chart.isRightToLeft()&&(b&&(b.x=this.chart.dim.width+(this.chart.offsets.l-this.chart.offsets.r)-b.x),a&&(a.x=this.chart.dim.width+(this.chart.offsets.l-this.chart.offsets.r)-a.x))}});return l});
//# sourceMappingURL=_IndicatorElement.js.map