/*** Table: raster_mosaic ***/

CREATE TABLE raster_mosaic (
    id integer NOT NULL,
    srs_id integer NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES resource (id),
    FOREIGN KEY (srs_id) REFERENCES srs (id)
);

COMMENT ON TABLE raster_mosaic IS 'raster_mosaic';

/*** Table: raster_mosaic_item ***/

CREATE TABLE raster_mosaic_item (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_id integer NOT NULL,
    display_name character varying,
    fileobj_id integer,
    footprint geometry(POLYGON, 4326),
    position integer,
    PRIMARY KEY (id),
    FOREIGN KEY (resource_id) REFERENCES raster_mosaic (id),
    FOREIGN KEY (fileobj_id) REFERENCES fileobj (id)
);

COMMENT ON TABLE raster_mosaic_item IS 'raster_mosaic';

CREATE INDEX idx_raster_mosaic_item_footprint ON raster_mosaic_item USING gist(footprint);
