from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, overload

from pyramid.request import Request as BaseRequest
from pyramid.response import Response

from nextgisweb.env import Env

if not TYPE_CHECKING:
    Request = BaseRequest

else:
    from nextgisweb.auth import User

    class Request[C](BaseRequest):
        @property
        def env(self) -> Env: ...

        @property
        def request_id(self) -> str: ...

        @property
        def is_api(self) -> bool: ...

        @property
        def path_param(self) -> Mapping[str, Any]: ...

        @property
        def context(self) -> C: ...

        def translate(self, value) -> Any: ...

        @property
        def user(self) -> User: ...

        def require_administrator(self) -> None: ...

        def require_authenticated(self) -> None: ...

        @overload
        def resource_permission(self, permission) -> None: ...

        @overload
        def resource_permission(self, permission, resource) -> None: ...

        def check_origin(self, origin: str) -> bool: ...

        def audit_context(self, model: str, id: int) -> None: ...

        # Pyramid stuff

        @property
        def response(self) -> Response: ...

        @property
        def registry(self) -> Any: ...

        @property
        def environ(self) -> dict[str, Any]: ...

        @property
        def authenticated_userid(self) -> int | None: ...

        @property
        def method(self) -> str: ...

        @property
        def url(self) -> str: ...

        @property
        def path_info(self) -> str: ...

        @property
        def matched_route(self) -> Any: ...

        @property
        def matchdict(self) -> dict[str, str]: ...

        @property
        def query_string(self) -> str: ...

        @property
        def params(self) -> dict[str, str]: ...

        @property
        def GET(self) -> dict[str, str]: ...

        @property
        def POST(self) -> dict[str, str]: ...

        def route_url(self, route_name: str, *elements, **kw) -> str: ...

        def route_path(self, route_name: str, *elements, **kw) -> str: ...

        def add_response_callback(self, callback) -> None: ...
