/*** Table: resource ***/

CREATE TABLE resource (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cls character varying NOT NULL,
    parent_id integer,
    keyname character varying,
    display_name character varying NOT NULL,
    creation_date timestamp without time zone NOT NULL,
    owner_user_id integer NOT NULL,
    description character varying,
    deletion_date timestamp without time zone,
    PRIMARY KEY (id),
    CHECK (parent_id IS NOT NULL OR id = 0),
    CONSTRAINT resource_parent_id_display_name_key UNIQUE (parent_id, display_name) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (parent_id) REFERENCES resource (id),
    UNIQUE (keyname),
    FOREIGN KEY (owner_user_id) REFERENCES auth_principal (id)
);

COMMENT ON TABLE resource IS 'resource';

/*** Table: resource_acl_rule ***/

CREATE TABLE resource_acl_rule (
    resource_id integer NOT NULL,
    principal_id integer NOT NULL,
    identity character varying NOT NULL,
    scope character varying NOT NULL,
    permission character varying NOT NULL,
    propagate boolean NOT NULL,
    action character varying NOT NULL,
    PRIMARY KEY (resource_id, principal_id, identity, scope, permission, propagate),
    FOREIGN KEY (resource_id) REFERENCES resource (id),
    FOREIGN KEY (principal_id) REFERENCES auth_principal (id)
);

COMMENT ON TABLE resource_acl_rule IS 'resource';

/*** Table: resource_favorite ***/

CREATE TABLE resource_favorite (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    resource_id integer NOT NULL,
    user_id integer NOT NULL,
    component character varying NOT NULL,
    kind character varying NOT NULL,
    created timestamp without time zone NOT NULL,
    label character varying,
    data jsonb NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (resource_id) REFERENCES resource (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES auth_principal (id) ON DELETE CASCADE
);

COMMENT ON TABLE resource_favorite IS 'resource';

/*** Table: resource_group ***/

CREATE TABLE resource_group (
    id integer NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES resource (id)
);

COMMENT ON TABLE resource_group IS 'resource';
